baseURL: https://qtdot.github.io/
title: 蘑菇蹲
languageCode: zh-cn
paginate: 5
theme: PaperMod

hasCJKLanguage: true

params:
    homeInfoParams:
        Title: 蘑菇蹲
        Content: 生活日常，无端咆哮和浴室偶思
    socialIcons: # optional
        - name: mastodon
          url: "https://m.cmx.im/@qwqky"
        - name: RSS
          url: "https://qtdot.github.io/blog/index.xml"

    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: true
    ShowToc: true
    ShowPostNavLinks: true
    ShowComments: true

    author: "煎蛋"

    comments: true
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: archives
      name: 归档
      url: /archives
      weight: 10
    - identifier: search
      name: 搜索
      url: /search/
      weight: 20
    - identifier: categories
      name: 分类
      url: /categories
      weight: 30
    - identifier: tags
      name: 标签
      url: /tags
      weight: 40
    - identifier: about
      name: 关于我
      url: /about
      weight: 50