baseURL: https://qtdot.github.io/blog/
title: 蘑菇蹲
defaultContentLanguage: zh
paginate: 5
theme: PaperMod

hasCJKLanguage: true

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
          - - $
            - $        
        enable: true

params:
    homeInfoParams:
        Title: 蘑菇蹲
        Content: 生活日常，无端咆哮和浴室偶思
    socialIcons: # optional
        - name: mastodon
          url: "https://m.cmx.im/@qwqky"
        - name: email
          url: "mailto:qtdotblog@duck.com"
        - name: RSS
          url: "https://qtdot.github.io/blog/posts/index.xml"

    ShowShareButtons: false
    ShowReadingTime: false
    ShowWordCount: true
    ShowToc: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true

    author: "煎蛋"

    comments: true
    
    # math: true
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: archives
      name: 归档
      url: /archives
      weight: 10
    - identifier: search
      name: 搜索
      url: /search/
      weight: 20
    - identifier: friends
      name: 友链
      url: /friends
      weight: 50
    - identifier: about
      name: 关于我
      url: /about
      weight: 60